[package]
name = "waters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
git2 = "0.16.1"

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
pretty_assertions = "1.3.0"
